### ISSUE TITLE
Remove NLog Dependency

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnetstandard#15]
In .NET Core, all library authors should be using the ILogger interface built into .NET Core.

This removes your dependency on specific logging frameworks and makes it so that developer can hook their own logger framework into the system via dependency injection.

For instance, we use Serilog, and not NLog as we find it is a much more capable and easy to use logging framework.

Remove NLog in all .NET Core projects and standardize on using ILogger interface as recommended.

**Comment by wehnertb** [comment]
For those who are finding the library failing because of a call to IsMaskingEnabled() - make sure you have a line in your NLog.config file that says:

<variable name="enableMasking" value="true" />

See this project for an example NLog.config (https://github.com/CyberSource/cybersource-rest-samples-csharp) - there is NO mention in either this library or the authentication library that you need to have your own NLog.config.

**Comment by wrightsonm** [comment]
we handled this in code for your system:

NLog.LogManager.Configuration.Variables.Add("enableMasking", new NLog.Layouts.SimpleLayout("true"));

**Comment by gnongsie** [comment]
Hi,

We have included a document to explain the changes to the logging framework in [Logging.md](https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/blob/master/cybersource-rest-client-netstandard/Logging.md).

Kindly refer to that document for details.

As @wehnertb explained, there is a sample NLog.config file in the [Sample Codes repository](https://github.com/CyberSource/cybersource-rest-samples-csharp).

I am closing this based on this.

**Comment by xantari** [comment]
You should not close this, you did not follow proper logging design guidance. Remove Nlog and use ILogger instead and all this becomes irrelevant.
