### ISSUE TITLE
Timeout setting in Configuration file is being ignored

### ISSUE THREAD

**Issue by wehnertb** [CyberSource/cybersource-rest-client-dotnetstandard#53]
I have dropped my Timeout to "5000" and I am still seeing calls taking 1.67 MINUTES before they finally cancel.

I am using a merchantkey and merchantid to authenticate and on top of seeing an awful lot of timeouts lately, I'm also seeing a lot of "authentication" errors.  I retry three times when I get a timeout - the pattern seems to be timeout, timeout, authentication failure.

Is there something else besides setting the timeout in the config do we need to do to have the SDK cancel the request if the timeout is reached?

The endpoint I'm posting to is: https://api.cybersource.com/pts/v2/payments/###############/captures  (where "##############" is the Authorizaton ID I need to capture.

On top of this, I am not seeing these requests show up in the Transaction Management portal at all.  These requests are for a US account on servers running in the US.

**Comment by wehnertb** [comment]
OK - looks like the offending code is here https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/blob/master/cybersource-rest-client-netstandard/cybersource-rest-client-netstandard/Client/Configuration.cs

You take a dictionary of values for the configuration and your examples explicitly show putting the timeout in this dictionary, however, you do not look at the dictionary to see if that value was set and set the timeout accordingly.

**Comment by gnongsie** [comment]
Hi @wehnertb,

The dictionary is being used in the Authentication SDK where it is used to populate a Configuration object with the required properties for the underlying HTTP Client. [Refer to the line](https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/blob/4ac46b30a3c14edbf869a81907de3d386f17079e/cybersource-rest-auth-netstandard/AuthenticationSdk/AuthenticationSdk/core/MerchantConfig.cs#L385)

However, this behavior is very concerning. Can you provide me with an example when this happened? As in a timestamp, along with the corresponding identifying values, so that I can check the logs on our end?

Please send it across to gnongsie@visa.com
